dev-version-ext = "pre"
pro-release-commit-message = "Released {{version}}, starting {{next_version}}"
pre-release-replacements = [
    {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"},
    {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}"}
]
